Repository galaxyproject/galaxy-hub, pull requests merged in 2022-09, with the labels that each got.

#1620 create index.md for next small scale meeting
  content/events/2022-09-small-scale/index.md
Labels: content

#1613 Add some more .eu posts
  content/events/2020-09-08-tools-platform-covid/index.md
  content/events/2022-04-international-proteomics/index.md
  content/events/2022-08-16-eurosciencegateway-kickoff-meeting/index.md
  content/news/2022-04-20-towards-sustainable-storage/index.md
  content/news/2022-04-24-tool-update/index.md
  content/news/2022-04-28-tiaas-hans-rudolf-lucille/index.md
  content/news/2022-06-27-gcc2022-webinar-mode/index.md
  content/news/2022-07-06-paper-tomas-teaching/index.md
  content/news/2022-08-10-open-admin-position/index.md
Labels: content, unification

#1622 Adding authorship to release announcements
  content/news/2022-08-galaxy-release-22-05/index.md
Labels: content

#1626 Change how NavBar subsite dropdown menu order is stored.
  config.json
  src/components/NavBar.vue
Labels: better-implementation

#1624 Updates EGD
  content/events/2022-10-egd/egd/index.md
  content/events/2022-10-egd/elixir-is2021/index.md
  content/events/2022-10-egd/esg/index.md
  content/events/2022-10-egd/index.md
Labels: content

#1630 Enable Regions dropdown for subsites other than Global
  src/components/NavBar.vue
Labels: unification

#1625 Create 2022-11-17 community call
  content/events/2022-11-17/index.md
Labels: content

#1631 Rework how Bundles are gathered, don't include HomeTop when empty.
  src/components/HomeTop.vue
  src/lib/pages.mjs
Labels: better-implementation, aesthetics

#1636 Swap community call weeks Oct27 and Nov17.
  content/events/2022-10-27-community-call/index.md
  content/events/2022-11-17-community-call/index.md
  content/events/2022-11-17/index.md
Labels: content

#1639 Add pointers to .eu from pages without full list of news/events
  content/belgium/events/main.md
  content/belgium/news/main.md
  content/elixir-it/events/main.md
  content/elixir-it/news/main.md
  content/erasmusmc/events/main.md
  content/erasmusmc/news/main.md
  content/eu/events/main.md
  content/eu/news/main.md
  content/freiburg/events/main.md
  content/freiburg/news/main.md
  content/genouest/events/main.md
  content/genouest/news/main.md
  content/ifb/events/main.md
  content/ifb/news/main.md
  content/pasteur/events/main.md
  content/pasteur/news/main.md
Labels: unification

#1641 Add vue-tweet-embed package
  package.json
  src/build/partition-content.mjs
  src/main.js
  yarn.lock
Labels: new-feature, dependencies

#1643 Add Flickr component
  src/components/Flickr.vue
  src/lib/client.mjs
Labels: new-feature

#1644 Replace existing Twitter component with a wrapper for the vue-tweet-embed ones
  content/bare/eu/usegalaxy/proteomics/index.md
  src/build/partition-content.mjs
  src/components/Twitter.vue
  src/main.js
Labels: better-implementation

#1646 Import news posts back to May 29, 2022
  content/news/2022-05-29-tool-update/index.md
  content/news/2022-06-19-tool-update/index.md
  content/news/2022-06-21-elixirah22/index.md
  content/news/2022-06-23-reached-50000-users/factsheet_automatable_eu.png
  content/news/2022-06-23-reached-50000-users/index.md
  content/news/2022-06-23-reached-50000-users/reached_50000_users.png
  content/news/2022-06-23-repurposing-covid-19-pipelines-for-the-monkeypox-virus/index.md
Labels: unification, migration

#1647 Fix bugs in contacts in article headers
  src/components/ArticleHeader.vue
Labels: bugfix

#1648 Add initial schedule EGD
  content/events/2022-10-egd/egd/index.md
  content/events/2022-10-egd/elixir-is2021/index.md
  content/events/2022-10-egd/index.md
Labels: content

#1650 Move margin below img-sizer images to outside the div
  src/assets/styles.scss
Labels: aesthetics

#1649 Update the COVID policy for the EGD
  content/events/2022-10-egd/index.md
Labels: content

#1653 Embed recording and add slides link
  content/events/2022-09-29-community-call/index.md
Labels: content

#1651 Launching Global Hub
  content/news/2022-09-28-global-hub/config-json-edit.png
  content/news/2022-09-28-global-hub/index.md
  content/news/2022-09-28-global-hub/subsite-tagging.png
  src/components/NavBar.vue
Labels: unification
