Repository galaxyproject/galaxy-hub, pull requests merged in 2022-06, with the labels that each got.

#1433 Fix some errors in some article metadata.
  content/events/2022-05-19-elixir-belgium/index.md
  content/events/2022-05-25-biodiversity/index.md
  content/news/2022-04-20-towards-sustainable-storage/index.md
Labels: content

#1435 Assign correct subsite metadata to a couple articles
  content/events/2022-05-19-elixir-belgium/index.md
  content/events/2022-05-25-biodiversity/index.md
Labels: content

#1443 Fix small typo in /events/gcc2022/abstracts/
  content/events/gcc2022/abstracts/index.md
Labels: content

#1444 Restore link to pre-2016 events archive.
  content/events/archive/main.md
Labels: content

#1445 Start a page documenting Hub development history.
  content/hub/history/index.md
Labels: content

#1446 Remove redundant .markdown class from BareArticles too.
  src/templates/BareArticle.vue
Labels: better-implementation

#1458 Change alert background color to national flag color
  content/bare/usegalaxy-eu/notices.md
  content/usegalaxy/welcome/main.md
Labels: aesthetics

#1452 Update eu subsite
  content/eu/jumbotron.md
  content/eu/main.md
  content/images/undraw-illustrations/citations.svg
  content/images/undraw-illustrations/communities.svg
  content/images/undraw-illustrations/projects.svg
  content/images/undraw-illustrations/team.svg
Labels: unification

#1464 Handle undefined/null urls in fix-links.mjs.
  src/build/fix-links.mjs
  src/lib/utils.js
Labels: bugfix

#1466 Fix some small mistakes and style issues in a few pages.
  content/community/arabic/index.md
  content/community/devroundtable/main.md
  content/get-started/index.md
Labels: content

#1447 Consolidate global styles into styles.scss.
  src/assets/styles.scss
  src/layouts/Default.vue
Labels: better-implementation

#1467 Fix #1215 by floating the body as well as the ToC.
  src/assets/styles.scss
  src/build/toc-remodel.mjs
Labels: bugfix

#1478 Add metabolomics.usegalaxy.eu's middle pane
  content/bare/usegalaxy-eu/metabolomics/index.md
Labels: hosted

#1486 Fix layout of ToC/body on Events.vue.
  src/components/pages/Events.vue
Labels: aesthetics, bugfix

#1487 Add /bare/eu/news/ and /bare/eu/events/
  content/bare/eu/events/main.md
  content/bare/eu/news/main.md
  src/pages/bare/eu/Events.vue
  src/pages/bare/eu/News.vue
Labels: unification

#1488 Remove extra </div> from covid19 homepage.
  content/projects/covid19/index.md
Labels: bugfix

#1490 Use <section> instead of <div> to wrap the ToC and body.
  src/build/toc-remodel.mjs
Labels: better-implementation

#1491 Make widgets for News and Events.
  content/bare/usegalaxy-eu/main/index.md
  src/pages/bare/eu/latest/Events.vue
  src/pages/bare/eu/latest/News.vue
Labels: unification

#1492 Replace /bare/eu/latest/ in the metabolomics middle pane too
  content/bare/usegalaxy-eu/metabolomics/index.md
Labels: unification

#1494 Fix links to /news/ and /events/ in /bare/eu/latest/ pages.
  src/pages/bare/eu/latest/Events.vue
  src/pages/bare/eu/latest/News.vue
Labels: bugfix

#1497 Reorganize urls for usegalaxy server middle panes
  content/bare/eu/usegalaxy/jobs.md
  content/bare/eu/usegalaxy/main/index.md
  content/bare/eu/usegalaxy/main/jumbotron.md
  content/bare/eu/usegalaxy/metabolomics/index.md
  content/bare/eu/usegalaxy/notices.md
Labels: unification, hosted

#1499 Add middle pane for proteomics.usegalaxy.eu.
  content/bare/eu/usegalaxy/proteomics/index.md
  content/images/galaxy-logos/galaxyp_banner.png
  src/assets/styles.scss
Labels: unification, hosted

#1500 Allow specifying a different Gitter room
  config.json
  content/bare/eu/usegalaxy/main/index.md
  content/bare/eu/usegalaxy/metabolomics/index.md
  content/bare/eu/usegalaxy/proteomics/index.md
  src/components/Gitter.vue
  src/layouts/Default.vue
Labels: unification, hosted

#1505 Update usegalaxy.eu middle pane jumbotron image
  content/bare/eu/usegalaxy/main/jumbotron.md
Labels: content, hosted
