Repository galaxyproject/galaxy-hub, pull requests merged in 2022-08, with the labels that each got.

#1566 Remove redundant paragraph
  content/blog/2022-07-25_Galaxy_Climate_Project_Introduction_Blog_2/index.md
Labels: content

#1571 Galaxy Well-being Blog 8
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/Decisions_Galaxy_Pie_Chart.png
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/Decisions_Other_Open_Source_Pie_Chart.png
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/Exclusion_Galaxy_Pie_Chart.png
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/Exclusion_Other_Open_Source_Pie_Chart.png
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/Lack_of_Sleep_Galaxy_Pie_Chart.png
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/Lack_of_Sleep_Other_Open_Source_Pie_Chart.png
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/Responsibility_Galaxy_Pie_Chart.png
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/Responsibility_Other_Open_Source_Pie_Chart.png
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/Roadmap_Galaxy_Pie_Chart.png
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/Roadmap_Other_Open_Source_Pie_Chart.png
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/Workload_Galaxy_Pie_Chart.png
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/Workload_Other_Open_Source_Pie_Chart.png
  content/blog/2022-08-05-Galaxy-Wellbeing-Blog-8/index.md
Labels: content

#1568 Redesign Homecards: light theme
  src/components/HomeCard.vue
  src/components/HomeProfile.vue
  src/components/ItemListBrief.vue
  src/components/pages/SubsiteHome.vue
  src/pages/Index.vue
  src/pages/bare/eu/latest/Events.vue
Labels: aesthetics

#1574 Center subsite names in the NavBar.
  src/components/NavBar.vue
Labels: aesthetics

#1575 Old content fixes
  content/admin/internals/data-model/index.md
  content/develop/linkbox.md
  content/develop/mercurial/index.md
  content/images/galaxy-logos/galaxy_project_logo_square_no_text_trans.png
  content/images/galaxy-logos/index.md
Labels: content

#1576 Customizable navbars
  navbars.json
  src/components/NavBar.vue
  src/components/NavBarItem.vue
Labels: unification

#1578 Simplify finding the default subsite.
  config.json
  gridsome.server.js
  src/components/Gitter.vue
  src/components/NavBar.vue
  src/layouts/Default.vue
  src/lib/site.js
  src/lib/utils.js
  src/templates/Platform.vue
Labels: better-implementation

#1584 Fix issue navigating between subsite homepages
  src/components/NavBar.vue
  src/components/pages/SubsiteHome.vue
Labels: bugfix

#1586 Display each subsite's custom footer instead of the global one
  src/layouts/Default.vue
Labels: unification

#1589 Store navbars in new yaml-based Dataset collection
  content/0examples/navbar.yml
  content/navbar.yml
  gridsome.config.js
  gridsome.server.js
  navbars.json
  package.json
  src/components/NavBar.vue
  src/lib/site.js
  yarn.lock
Labels: dependencies, better-implementation

#1594 Datasets: use existing filename attribute instead of "type"
  gridsome.server.js
  src/components/NavBar.vue
Labels: better-implementation

#1582 First draft of custom navbar for each subsite
  content/belgium/navbar.yml
  content/elixir-it/navbar.yml
  content/erasmusmc/navbar.yml
  content/eu/navbar.yml
  content/freiburg/navbar.yml
  content/genouest/navbar.yml
  content/ifb/navbar.yml
  content/pasteur/navbar.yml
Labels: unification

#1600 Move the NavBar styling info from config.json to the navbar.yml files
  config.json
  content/elixir-it/navbar.yml
  content/erasmusmc/navbar.yml
  content/eu/navbar.yml
  content/genouest/navbar.yml
  content/ifb/navbar.yml
  content/pasteur/navbar.yml
  content/us/navbar.yml
  gridsome.server.js
  package.json
  src/components/NavBar.vue
Labels: dependencies, better-implementation

#1608 Remove subsite middle panes
  content/bare/belgium/galaxy/index.md
  content/bare/belgium/notices.md
  content/bare/erasmusmc/galaxy/index.md
  content/bare/erasmusmc/notices.md
  content/bare/freiburg/galaxy/credits.md
  content/bare/freiburg/galaxy/index.md
  content/bare/freiburg/notices.md
  content/bare/genouest/galaxy/index.md
  content/bare/genouest/notices.md
  content/bare/ifb/galaxy/index.md
  content/bare/ifb/notices.md
  content/bare/pasteur/galaxy/index.md
  content/bare/pasteur/notices.md
  src/pages/bare/belgium/latest/NewsEvents.vue
  src/pages/bare/elixir-it/latest/NewsEvents.vue
  src/pages/bare/erasmusmc/latest/NewsEvents.vue
  src/pages/bare/freiburg/latest/NewsEvents.vue
  src/pages/bare/genouest/latest/NewsEvents.vue
  src/pages/bare/ifb/latest/NewsEvents.vue
  src/pages/bare/pasteur/latest/NewsEvents.vue
Labels: unification

#1614 Update GCC image on usegalaxy.org middle pane
  content/usegalaxy/welcome/main.md
Labels: content, hosted
