Repository galaxyproject/galaxy-hub, pull requests merged in 2022-01, with the labels that each got.

#1092 LinkBox: Add metadata options like `horizontal` and `style`.
  content/events/gcc2013/abstracts/index.md
  content/events/gcc2013/abstracts/posters/index.md
  content/events/gcc2013/abstracts/talks/index.md
  content/events/gcc2013/bof/clinical-use-hpc-file-systems/index.md
  content/events/gcc2013/bof/galaxy-admins/index.md
  content/events/gcc2013/bof/galaxy-blast/index.md
  content/events/gcc2013/bof/galaxy-professionals/index.md
  content/events/gcc2013/bof/index.md
  content/events/gcc2013/bof/proteomics/index.md
  content/events/gcc2013/bof/public-galaxy-servers/index.md
  content/events/gcc2013/bof/tool-developers/index.md
  content/events/gcc2013/index.md
  content/events/gcc2013/key-dates/index.md
  content/events/gcc2013/lightning/index.md
  content/events/gcc2013/linkbox.json
  content/events/gcc2013/links.json
  content/events/gcc2013/logistics/index.md
  content/events/gcc2013/organizers/index.md
  content/events/gcc2013/photos/index.md
  content/events/gcc2013/program/index.md
  content/events/gcc2013/promotion/index.md
  content/events/gcc2013/register/index.md
  content/events/gcc2013/sponsorships/index.md
  content/events/gcc2013/training-day/advance-tool-data/index.md
  content/events/gcc2013/training-day/api/index.md
  content/events/gcc2013/training-day/index.md
  content/events/gcc2013/training-day/intro-tool-data/index.md
  content/events/gcc2013/training-day/vms/index.md
  cypress/integration/main.spec.js
  src/assets/styles.scss
  src/components/LinkBox.vue
Labels: enhancement

#1106 Fix <pre> code block font colors.
  src/assets/styles.scss
  src/layouts/Default.vue
Labels: aesthetics, bugfix

#1101 New COVID portal
  config.json
  content/covid19/analyses/index.md
  content/covid19/data/index.md
  content/covid19/genomics/global-platform/caller_comparison_fig1.png
  content/covid19/genomics/global-platform/caller_comparison_fig2.png
  content/covid19/genomics/global-platform/export_url_colab_gif.gif
  content/covid19/genomics/global-platform/fig1.png
  content/covid19/genomics/global-platform/fig2.png
  content/covid19/genomics/global-platform/history_import_gif.gif
  content/covid19/genomics/global-platform/index.md
  content/covid19/genomics/global-platform/workflow_import_gif.gif
  content/covid19/genomics/no-more-business-as-usual/3-MRCA/index.md
  content/covid19/genomics/no-more-business-as-usual/3-MRCA/mrca_wf.png
  content/covid19/genomics/no-more-business-as-usual/7-variants-description/rd-rp/index.md
  content/covid19/genomics/no-more-business-as-usual/7-variants-description/rd-rp/nsp7-8-12-complex.jpg
  content/covid19/genomics/no-more-business-as-usual/index.md
  content/covid19/index.md
  content/covid19/samples/index.md
  content/covid19/workflows/index.md
  content/images/covid19/baker_2020.png
  content/images/covid19/image.png
  content/images/covid19/maier_2021.png
  content/images/covid19/martin_2021.png
  content/images/covid19/mei_2021.png
  content/images/covid19/variant-frequency.svg
  content/site-footer.md
  src/components/NavBar.vue
Labels: WIP

#1123 Redirect component and cancel button
  src/components/ArticleHeader.vue
  src/components/Redirect.vue
  src/pages/404.vue
  src/utils.js
Labels: enhancement, better-implementation

#1124 New Contributing page
  content/community/contributing/index.md
  content/images/undraw-illustrations/contribute.svg
  src/components/NavBar.vue
Labels: content

#1135 add link for today's slides
  content/events/2022-01-small-scale/index.md
Labels: content

#1141 added gene-specific allele frequency maps
  content/projects/covid19/analyses/index.md
  content/projects/covid19/non-synonymous-coding-3cpro/index.md
  content/projects/covid19/non-synonymous-coding-e/index.md
  content/projects/covid19/non-synonymous-coding-endor/index.md
  content/projects/covid19/non-synonymous-coding-exon/index.md
  content/projects/covid19/non-synonymous-coding-helicase/index.md
  content/projects/covid19/non-synonymous-coding-leader/index.md
  content/projects/covid19/non-synonymous-coding-m/index.md
  content/projects/covid19/non-synonymous-coding-methtr/index.md
  content/projects/covid19/non-synonymous-coding-n/index.md
  content/projects/covid19/non-synonymous-coding-nsp10/index.md
  content/projects/covid19/non-synonymous-coding-nsp11/index.md
  content/projects/covid19/non-synonymous-coding-nsp2/index.md
  content/projects/covid19/non-synonymous-coding-nsp3/index.md
  content/projects/covid19/non-synonymous-coding-nsp4/index.md
  content/projects/covid19/non-synonymous-coding-nsp6/index.md
  content/projects/covid19/non-synonymous-coding-nsp7/index.md
  content/projects/covid19/non-synonymous-coding-nsp8/index.md
  content/projects/covid19/non-synonymous-coding-nsp9/index.md
  content/projects/covid19/non-synonymous-coding-orf10/index.md
  content/projects/covid19/non-synonymous-coding-orf3a/index.md
  content/projects/covid19/non-synonymous-coding-orf6/index.md
  content/projects/covid19/non-synonymous-coding-orf7a/index.md
  content/projects/covid19/non-synonymous-coding-orf7b/index.md
  content/projects/covid19/non-synonymous-coding-orf8/index.md
  content/projects/covid19/non-synonymous-coding-rdrp/index.md
  content/projects/covid19/non-synonymous-coding-s/index.md
  content/projects/covid19/synonymous-coding-3cpro/index.md
  content/projects/covid19/synonymous-coding-e/index.md
  content/projects/covid19/synonymous-coding-endor/index.md
  content/projects/covid19/synonymous-coding-exon/index.md
  content/projects/covid19/synonymous-coding-helicase/index.md
  content/projects/covid19/synonymous-coding-leader/index.md
  content/projects/covid19/synonymous-coding-m/index.md
  content/projects/covid19/synonymous-coding-methtr/index.md
  content/projects/covid19/synonymous-coding-n/index.md
  content/projects/covid19/synonymous-coding-nsp10/index.md
  content/projects/covid19/synonymous-coding-nsp11/index.md
  content/projects/covid19/synonymous-coding-nsp2/index.md
  content/projects/covid19/synonymous-coding-nsp3/index.md
  content/projects/covid19/synonymous-coding-nsp4/index.md
  content/projects/covid19/synonymous-coding-nsp6/index.md
  content/projects/covid19/synonymous-coding-nsp7/index.md
  content/projects/covid19/synonymous-coding-nsp8/index.md
  content/projects/covid19/synonymous-coding-nsp9/index.md
  content/projects/covid19/synonymous-coding-orf10/index.md
  content/projects/covid19/synonymous-coding-orf3a/index.md
  content/projects/covid19/synonymous-coding-orf6/index.md
  content/projects/covid19/synonymous-coding-orf7a/index.md
  content/projects/covid19/synonymous-coding-orf7b/index.md
  content/projects/covid19/synonymous-coding-orf8/index.md
  content/projects/covid19/synonymous-coding-rdrp/index.md
  content/projects/covid19/synonymous-coding-s/index.md
Labels: projects-covid

#1144 Fix site-wide footer layout.
  src/layouts/Default.vue
Labels: aesthetics, bugfix

#1150 Add social preview <head> meta tags.
  config.json
  src/components/ArticleHeader.vue
  src/templates/Article.vue
  src/templates/VueArticle.vue
  src/utils.js
Labels: enhancement

#1147 Fix HomeProfile top/bottom spacing.
  src/components/HomeProfile.vue
  src/pages/Index.vue
Labels: paper-cut, aesthetics

#1154 Use doi link to zenodo record
  content/projects/covid19/workflows/index.md
Labels: content
